//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use super::role::Role;
use super::status::Status;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub email: String,
    pub password_hash: String,
    pub role: Role,
    pub status: Status,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::financial_records::Entity")]
    FinancialRecords,
}

impl Related<super::financial_records::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FinancialRecords.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
